# Build nativo deve ser feito localmente primeiro:
# mvn clean package -Pnative -DskipTests

# Runtime mínimo para executável nativo
FROM quay.io/quarkus/quarkus-micro-image:2.0
WORKDIR /work/
COPY target/*-runner /work/application
RUN chmod 775 /work /work/application
EXPOSE 8080
ENV PORT=8080
ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
